// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-2Bv_D9s0ze2E_7NdrRbFcpw1jLE7JBI',
    appId: '1:489556255818:web:6b78d090bf33895e39f2b3',
    messagingSenderId: '489556255818',
    projectId: 'hop-app-v1-2024',
    authDomain: 'hop-app-v1-2024.firebaseapp.com',
    storageBucket: 'hop-app-v1-2024.appspot.com',
    measurementId: 'G-EG8KTTCR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlQakjEP-c5hhC-Q51Lho-OH0CZtPmFVA',
    appId: '1:489556255818:android:60595442deb721d439f2b3',
    messagingSenderId: '489556255818',
    projectId: 'hop-app-v1-2024',
    storageBucket: 'hop-app-v1-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLAWqmZ_rlhsqd8C4I-zM4r8L-4vauOCc',
    appId: '1:489556255818:ios:bfabc936a8d5044739f2b3',
    messagingSenderId: '489556255818',
    projectId: 'hop-app-v1-2024',
    storageBucket: 'hop-app-v1-2024.appspot.com',
    iosBundleId: 'com.example.hopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLAWqmZ_rlhsqd8C4I-zM4r8L-4vauOCc',
    appId: '1:489556255818:ios:94839a0010a246e439f2b3',
    messagingSenderId: '489556255818',
    projectId: 'hop-app-v1-2024',
    storageBucket: 'hop-app-v1-2024.appspot.com',
    iosBundleId: 'com.example.hopApp.RunnerTests',
  );
}
